import { GitCompareArrows, PauseCircle, Search } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { parseYouTubeInput, verifyVideoIds } from '../lib/youtube'
import { loadYouTubeApi, playerEngine, type YouTubePlayer } from '../player/PlayerEngine'
import { useApp } from '../store/AppStore'

export default function ComparePage() {
  const app = useApp(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const [aInput, setAInput] = useState(params.get('a') ?? ''); const [bInput, setBInput] = useState(params.get('b') ?? '')
  const aHost = useRef<HTMLDivElement>(null); const bHost = useRef<HTMLDivElement>(null); const players = useRef<{ a?: YouTubePlayer; b?: YouTubePlayer }>({})
  const a = params.get('a'); const b = params.get('b')
  useEffect(() => { playerEngine.pause(); if (!a || !b || !aHost.current || !bHost.current) return; let active = true; void loadYouTubeApi().then((YT) => { if (!active || !aHost.current || !bHost.current) return; players.current.a = new YT.Player(aHost.current, { videoId: a, width: '100%', height: '100%', playerVars: { controls: 1, playsinline: 1, origin: window.location.origin }, events: { onStateChange: (e: { data: number }) => { if (e.data === 1) players.current.b?.pauseVideo() } } }); players.current.b = new YT.Player(bHost.current, { videoId: b, width: '100%', height: '100%', playerVars: { controls: 1, playsinline: 1, origin: window.location.origin }, events: { onStateChange: (e: { data: number }) => { if (e.data === 1) players.current.a?.pauseVideo() } } }) }); return () => { active = false; players.current.a?.destroy(); players.current.b?.destroy(); players.current = {} } }, [a, b])
  const resolve = (value: string) => parseYouTubeInput(value)?.id ?? (/^[A-Za-z0-9_-]{11}$/.test(value.trim()) ? value.trim() : '')
  const load = async () => { const first = resolve(aInput), second = resolve(bInput); if (!first || !second || first === second) { app.notify('異なる2つのVideo IDまたはURLを指定してください', 'error'); return } try { const result = await verifyVideoIds([first, second]); app.upsertVideos(result.valid) } catch { /* embed verification remains available */ } setParams({ a: first, b: second }) }
  const align = () => { const source = players.current.a, target = players.current.b; if (!source || !target) return; const durationA = source.getDuration(), durationB = target.getDuration(); if (durationA && durationB) target.seekTo(source.getCurrentTime() / durationA * durationB, true) }
  return <div className="page compare-page"><div className="page-heading"><div><span className="eyebrow">SIDE BY SIDE</span><h1>Compare</h1><p>同時再生は禁止。片方がPlayになると、もう片方を自動Pauseします。</p></div></div><div className="compare-picker"><label>Video A<input value={aInput} onChange={(e) => setAInput(e.target.value)} placeholder="YouTube URL / Video ID" /></label><label>Video B<input value={bInput} onChange={(e) => setBInput(e.target.value)} placeholder="YouTube URL / Video ID" /></label><button className="primary-button" onClick={() => void load()}><Search />読み込む</button></div>{a && b ? <><div className="compare-workspace"><div><div className="compare-frame" ref={aHost} /><h2>{app.state.videos[a]?.title ?? `Video ${a}`}</h2><button className="text-button" onClick={() => navigate(`/watch?v=${a}`)}>Watchで開く</button></div><div><div className="compare-frame" ref={bHost} /><h2>{app.state.videos[b]?.title ?? `Video ${b}`}</h2><button className="text-button" onClick={() => navigate(`/watch?v=${b}`)}>Watchで開く</button></div></div><div className="compare-tools"><button className="secondary-button" onClick={() => { players.current.a?.pauseVideo(); players.current.b?.pauseVideo() }}><PauseCircle />両方Pause</button><button className="primary-button" onClick={align}><GitCompareArrows />Aと同じ割合へBを移動</button></div></> : <div className="compare-empty"><GitCompareArrows /><h2>比較する2本を選択</h2><p>Video Cardの長押しメニューから1本目を追加することもできます。</p></div>}</div>
}
