import { ArrowDown, ArrowUp, GripVertical, ListVideo, Play, RefreshCw, Save, Shuffle, Trash2, WandSparkles } from 'lucide-react'
import { useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import type { AutoAddRule } from '../domain/types'
import { formatDuration } from '../lib/time'
import { applyAutoAddRules, applyRuntimeFeatureRules, applyVisibilityRules } from '../lib/videoRules'
import { useApp } from '../store/AppStore'

export default function QueuePage() {
  const app = useApp(); const navigate = useNavigate(); const [name, setName] = useState(''); const [ruleName, setRuleName] = useState(''); const [channelId, setChannelId] = useState(''); const [include, setInclude] = useState(''); const [exclude, setExclude] = useState(''); const [categoryId, setCategoryId] = useState(''); const [maxDuration, setMaxDuration] = useState(''); const [liveRule, setLiveRule] = useState<'any' | 'yes' | 'no'>('any'); const [shortsRule, setShortsRule] = useState<'any' | 'yes' | 'no'>('any'); const [publishedDays, setPublishedDays] = useState('')
  const [draggingId, setDraggingId] = useState<string>()
  const dragIndex = useRef(-1)
  const dragMoved = useRef(false)
  const startReorder = (index: number, itemId: string, event: ReactPointerEvent<HTMLButtonElement>) => {
    if (!event.isPrimary || event.button !== 0) return
    event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId)
    dragIndex.current = index; dragMoved.current = false; setDraggingId(itemId)
  }
  const moveReorder = (event: ReactPointerEvent<HTMLButtonElement>) => {
    if (!draggingId || dragIndex.current < 0) return
    const row = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>('[data-queue-index]')
    const target = Number(row?.dataset.queueIndex)
    if (!Number.isInteger(target) || target === dragIndex.current || target < 0 || target >= app.state.queue.length) return
    app.reorderQueue(dragIndex.current, target); dragIndex.current = target; dragMoved.current = true
  }
  const finishReorder = (event: ReactPointerEvent<HTMLButtonElement>) => {
    if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId)
    if (dragMoved.current) app.notify('Queueの順番を更新しました', 'success')
    dragIndex.current = -1; dragMoved.current = false; setDraggingId(undefined)
  }
  const addRule = () => { if (!ruleName.trim()) return; const rule: AutoAddRule = { id: crypto.randomUUID(), name: ruleName.trim(), enabled: true, channelId: channelId.trim() || undefined, includeKeyword: include.trim() || undefined, excludeKeyword: exclude.trim() || undefined, categoryId: categoryId.trim() || undefined, maxDuration: maxDuration ? Number(maxDuration) : undefined, live: app.feature('live') && liveRule !== 'any' ? liveRule === 'yes' : undefined, shorts: app.feature('shorts') && shortsRule !== 'any' ? shortsRule === 'yes' : undefined, publishedWithinDays: publishedDays ? Number(publishedDays) : undefined, updatedAt: new Date().toISOString() }; app.replaceState((current) => ({ ...current, autoAddRules: [...current.autoAddRules, rule] })); setRuleName(''); setChannelId(''); setInclude(''); setExclude(''); setCategoryId(''); setMaxDuration(''); setLiveRule('any'); setShortsRule('any'); setPublishedDays('') }
  const evaluateRules = () => { const candidates = applyRuntimeFeatureRules(applyVisibilityRules(Object.values(app.state.videos), app.state.settings), { shorts: app.feature('shorts'), live: app.feature('live') }); const additions = applyAutoAddRules(candidates, app.state.autoAddRules, app.state.queue); if (additions.length) app.applyRefreshResults([], additions); app.notify(additions.length ? `${additions.length}本を追加しました` : '条件に合う新しい動画はありません') }
  const playFirst = () => {
    const video = app.state.queue[0]?.video
    if (!video) return
    app.playNext()
    navigate(`/watch?v=${video.videoId}`)
  }
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">NOW & NEXT</span><h1>Queue</h1><p>現在Sessionで近いうちに見るordered listです。Playlistとは分離されています。</p></div><div className="heading-actions"><button className="secondary-button" onClick={app.shuffleQueue} disabled={app.state.queue.length < 2}><Shuffle />Shuffle</button><button className="primary-button" onClick={playFirst} disabled={!app.state.queue.length}><Play />先頭を再生</button></div></div>
    {app.state.queue.length ? <div className={`queue-list ${draggingId ? 'is-reordering' : ''}`}>{app.state.queue.map((item, index) => <div className={`queue-row ${draggingId === item.id ? 'dragging' : ''}`} data-queue-index={index} key={item.id}><button className="queue-drag-handle" aria-label={`${item.video.title}をドラッグして並び替え`} aria-pressed={draggingId === item.id} onPointerDown={(event) => startReorder(index, item.id, event)} onPointerMove={moveReorder} onPointerUp={finishReorder} onPointerCancel={finishReorder}><GripVertical /></button><span className="queue-index">{String(index + 1).padStart(2, '0')}</span><img src={item.video.thumbnail ?? `https://i.ytimg.com/vi/${item.video.videoId}/mqdefault.jpg`} alt="" /><button className="queue-title" onClick={() => { app.playQueueItem(item.id); navigate(`/watch?v=${item.video.videoId}`) }}><strong>{item.video.title}</strong><span>{item.video.channelTitle} · {formatDuration(item.video.durationSeconds)}</span></button><div className="queue-row-actions"><button className="icon-button" disabled={index === 0} onClick={() => app.reorderQueue(index, index - 1)} aria-label="上へ"><ArrowUp /></button><button className="icon-button" disabled={index === app.state.queue.length - 1} onClick={() => app.reorderQueue(index, index + 1)} aria-label="下へ"><ArrowDown /></button><button className="icon-button danger-hover" onClick={() => app.removeQueue(item.id)} aria-label="削除"><Trash2 /></button></div></div>)}</div> : <EmptyState icon={ListVideo} title="Queueは空です" description="Video Cardを長押しして、次に再生またはQueueへ追加できます。" />}
    <section className="settings-section"><div className="section-heading"><div><span className="section-kicker"><WandSparkles /></span><h2>Auto Add Rules</h2></div><button className="secondary-button" onClick={evaluateRules}><RefreshCw />Manual Refresh</button></div><p>Home / 手動Refresh時だけ評価します。Background pollingは行わず、1 Ruleにつき最大20本です。</p><div className="smart-builder"><input value={ruleName} onChange={(e) => setRuleName(e.target.value)} placeholder="Rule名" /><input value={channelId} onChange={(e) => setChannelId(e.target.value)} placeholder="Channel ID（任意）" /><input value={include} onChange={(e) => setInclude(e.target.value)} placeholder="含むKeyword" /><input value={exclude} onChange={(e) => setExclude(e.target.value)} placeholder="除外Keyword" /><input value={categoryId} onChange={(e) => setCategoryId(e.target.value)} placeholder="Category ID" /><input type="number" min="1" value={maxDuration} onChange={(e) => setMaxDuration(e.target.value)} placeholder="最大秒数" />{app.feature('live') && <select value={liveRule} onChange={(e) => setLiveRule(e.target.value as typeof liveRule)}><option value="any">Live: Any</option><option value="yes">Liveのみ</option><option value="no">Live除外</option></select>}{app.feature('shorts') && <select value={shortsRule} onChange={(e) => setShortsRule(e.target.value as typeof shortsRule)}><option value="any">Shorts: Any</option><option value="yes">Shortsのみ</option><option value="no">Shorts除外</option></select>}<input type="number" min="1" value={publishedDays} onChange={(e) => setPublishedDays(e.target.value)} placeholder="公開からN日以内" /><button className="primary-button" onClick={addRule}>作成</button></div><div className="saved-queue-grid">{app.state.autoAddRules.map((rule) => <article className="saved-queue-card" key={rule.id}><div><strong>{rule.name}</strong><span>{rule.enabled ? 'ON' : 'OFF'}</span></div><p>{[rule.channelId && `Channel ${rule.channelId}`, rule.includeKeyword && `Include ${rule.includeKeyword}`, rule.excludeKeyword && `Exclude ${rule.excludeKeyword}`, rule.categoryId && `Category ${rule.categoryId}`, rule.maxDuration && `≤ ${rule.maxDuration}秒`, app.feature('live') && rule.live !== undefined && (rule.live ? 'Liveのみ' : 'Live除外'), app.feature('shorts') && rule.shorts !== undefined && (rule.shorts ? 'Shortsのみ' : 'Shorts除外'), rule.publishedWithinDays && `${rule.publishedWithinDays}日以内`].filter(Boolean).join(' · ') || 'すべての候補'}</p><div><button onClick={() => app.replaceState((current) => ({ ...current, autoAddRules: current.autoAddRules.map((item) => item.id === rule.id ? { ...item, enabled: !item.enabled, updatedAt: new Date().toISOString() } : item) }))}>{rule.enabled ? 'Disable' : 'Enable'}</button><button className="danger-text" onClick={() => app.replaceState((current) => ({ ...current, autoAddRules: current.autoAddRules.filter((item) => item.id !== rule.id) }))}>Delete</button></div></article>)}</div></section>
    {app.feature('savedQueue') && <section className="settings-section"><div className="section-heading"><div><span className="section-kicker"><Save /></span><h2>Saved Queue</h2></div></div><div className="inline-form"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Snapshot名" maxLength={80} /><button className="secondary-button" onClick={() => { app.saveQueue(name); setName('') }} disabled={!name.trim() || app.state.savedQueues.length >= 100}>現在のQueueを保存</button></div><div className="saved-queue-grid">{app.state.savedQueues.map((saved) => <article className="saved-queue-card" key={saved.id}><div><strong>{saved.name}</strong><span>{saved.items.length}本</span></div><div><button onClick={() => app.loadSavedQueue(saved.id)}>Replace</button><button onClick={() => app.loadSavedQueue(saved.id, 'append')}>Append</button><button className="danger-text" onClick={() => confirm('このSaved Queueを削除しますか？') && app.deleteSavedQueue(saved.id)}>Delete</button></div></article>)}</div></section>}
  </div>
}
