import { Activity, ArrowDown, ArrowUp, Cloud, Database, Eye, Filter, Home, LayoutGrid, LogIn, MonitorCog, Moon, Palette, PanelLeft, RefreshCw, ShieldCheck, SlidersHorizontal, Sun, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { featureChildren, featureGroups, featureLabels } from '../config/features'
import { createDefaultState } from '../config/features'
import { dbClear, DB_VERSION } from '../data/db'
import type { ThemeMode } from '../domain/types'
import { APP_VERSION, getDiagnostics, recordDiagnostic, subscribeDiagnostics } from '../lib/diagnostics'
import { rehydrateReferencedVideos } from '../sync/rehydrate'
import { getSupabase, signInWithGoogle, signOutCloud, syncState } from '../sync/supabase'
import { useApp } from '../store/AppStore'

export default function SettingsPage() {
  const app = useApp(); const [syncing, setSyncing] = useState(false); const [diagnostics, setDiagnostics] = useState(getDiagnostics); const [cloudIdentity, setCloudIdentity] = useState<string | null | undefined>(undefined)
  const settings = app.state.settings
  const supabase = getSupabase()
  const setMode = (mode: ThemeMode) => app.patchSettings({ theme: { ...settings.theme, mode } })
  const move = (items: string[], index: number, direction: -1 | 1) => { const next = [...items]; const target = index + direction; if (target < 0 || target >= next.length) return items; [next[index], next[target]] = [next[target], next[index]]; return next }
  const toggleSpeedPreset = (rate: number) => {
    const selected = settings.playback.speedPresets.includes(rate)
    if ((selected && settings.playback.speedPresets.length === 1) || (!selected && settings.playback.speedPresets.length >= 8)) return
    const speedPresets = (selected ? settings.playback.speedPresets.filter((item) => item !== rate) : [...settings.playback.speedPresets, rate]).sort((a, b) => a - b)
    app.patchSettings({ playback: { ...settings.playback, speedPresets } })
  }
  useEffect(() => subscribeDiagnostics(() => setDiagnostics(getDiagnostics())), [])
  useEffect(() => {
    if (!supabase) { setCloudIdentity(null); return }
    let active = true
    void supabase.auth.getSession().then(({ data, error }) => {
      if (!active) return
      if (error) recordDiagnostic('sync', 'Cloud auth session restore failed')
      setCloudIdentity(data.session?.user.email ?? data.session?.user.id ?? null)
    })
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      if (active) setCloudIdentity(session?.user.email ?? session?.user.id ?? null)
    })
    return () => { active = false; subscription.unsubscribe() }
  }, [supabase])
  const connectGoogle = async () => { try { await signInWithGoogle() } catch (error) { recordDiagnostic('sync', 'Google sign-in failed'); app.notify(error instanceof Error ? error.message : 'Google sign-in failed', 'error') } }
  const disconnectCloud = async () => { try { await signOutCloud(); app.notify('Cloud sessionを解除しました。Local dataは保持されています', 'success') } catch (error) { app.notify(error instanceof Error ? error.message : 'Logout failed', 'error') } }
  const runSync = async () => { if (!settings.cloudSync) { app.notify('Cloud SyncをONにしてください', 'error'); return } setSyncing(true); try { const result = await syncState(app.state); const hydrated = await rehydrateReferencedVideos(result); app.acceptExternalState(hydrated); app.notify('Cloud Syncが完了しました', 'success') } catch (e) { recordDiagnostic('sync', 'Cloud sync failed'); app.notify(e instanceof Error ? e.message : 'Sync failed', 'error') } finally { setSyncing(false) } }
  const clearLocal = async () => { if (!confirm('この端末のすべてのVistaPlayデータを削除しますか？この操作は元に戻せません。')) return; for (const store of ['settings', 'videos', 'queue', 'progress', 'sessions', 'library', 'cache', 'migrations'] as const) await dbClear(store); app.acceptExternalState(createDefaultState()); app.closePlayer(); app.notify('この端末のデータを削除しました', 'success') }
  return <div className="page settings-page"><div className="page-heading"><div><span className="eyebrow">CONTROL CENTER</span><h1>Settings</h1><p>機能をOFFにすると関連UIは消えますが、保存済み設定とデータは維持されます。</p></div></div>
    <section className="settings-section"><div className="settings-title"><Palette /><div><h2>Appearance</h2><p>明るく、余白のあるProductivity UI。</p></div></div><div className="setting-grid"><div className="setting-item"><span>Theme</span><div className="segmented">{([['light', Sun], ['dark', Moon], ['system', MonitorCog]] as const).map(([mode, Icon]) => <button className={settings.theme.mode === mode ? 'active' : ''} onClick={() => setMode(mode)} key={mode}><Icon />{mode}</button>)}</div></div><label className="setting-item"><span>Surface</span><select value={settings.theme.surface} onChange={(e) => app.patchSettings({ theme: { ...settings.theme, surface: e.target.value as any } })}><option value="neutral">Neutral</option><option value="warm">Warm</option><option value="cool">Cool</option></select></label><label className="setting-item"><span>Accent</span><div className="color-setting"><input type="color" value={settings.theme.accent} onChange={(e) => app.patchSettings({ theme: { ...settings.theme, accent: e.target.value } })} /><input value={settings.theme.accent} pattern="#[0-9a-fA-F]{6}" onChange={(e) => /^#[0-9a-fA-F]{6}$/.test(e.target.value) && app.patchSettings({ theme: { ...settings.theme, accent: e.target.value } })} /></div></label></div></section>
    <section className="settings-section" id="features"><div className="settings-title"><SlidersHorizontal /><div><h2>Features</h2><p>Core playback・Search・Basic Library・History・Settings・Theme・Basic QueueはOFF不可。</p></div></div><div className="feature-groups">{featureGroups.map((group) => <div className="feature-group" key={group.label}><h3>{group.label}</h3>{group.keys.map((key) => <div className="feature-toggle-set" key={key}><label className="toggle-row"><span><strong>{featureLabels[key]}</strong></span><input type="checkbox" role="switch" checked={settings.features[key]} onChange={(event) => app.setFeature(key, event.target.checked)} /><i /></label>{featureChildren[key]?.map((child) => <label className="toggle-row dependent-toggle" key={child}><span><strong>{featureLabels[child]}</strong><small>{settings.features[key] ? '個別に表示を制御' : `${featureLabels[key]} OFF中はruntime無効`}</small></span><input type="checkbox" role="switch" checked={settings.features[child]} disabled={!settings.features[key]} onChange={(event) => app.setFeature(child, event.target.checked)} /><i /></label>)}</div>)}</div>)}</div></section>
    <section className="settings-section"><div className="settings-title"><LayoutGrid /><div><h2>Layout</h2><p>幅の設定はこの端末だけに保存されます。</p></div></div><div className="setting-grid"><label className="setting-item"><span>Sidebar</span><select value={settings.layout.sidebarMode} onChange={(e) => app.patchSettings({ layout: { ...settings.layout, sidebarMode: e.target.value as any } })}><option value="expanded">184px</option><option value="compact">72px</option><option value="hidden">Hidden</option></select></label><label className="setting-item"><span>Card size</span><select value={settings.layout.cardSize} onChange={(e) => app.patchSettings({ layout: { ...settings.layout, cardSize: e.target.value as any } })}><option value="compact">Compact</option><option value="comfortable">Comfortable</option><option value="large">Large</option></select></label><label className="setting-item"><span>Right pane {settings.layout.rightPaneWidth}px</span><input type="range" min="300" max="520" value={settings.layout.rightPaneWidth} onChange={(e) => app.patchSettings({ layout: { ...settings.layout, rightPaneWidth: Number(e.target.value) } })} /></label><label className="setting-item"><span>Default Watch tab</span><select value={settings.layout.defaultWatchTab} onChange={(e) => app.patchSettings({ layout: { ...settings.layout, defaultWatchTab: e.target.value } })}><option value="queue">Queue</option>{app.feature('chapters') && <option value="chapters">Chapters</option>}{app.feature('comments') && <option value="comments">Comments</option>}{app.feature('captions') && <option value="captions">Captions</option>}<option value="overview">Overview</option></select></label><label className="toggle-row"><span><strong>Focus Mode</strong><small>Player・Title・Controls・Chapters・Captionsだけに集中</small></span><input type="checkbox" checked={settings.layout.focusMode} onChange={(e) => app.patchSettings({ layout: { ...settings.layout, focusMode: e.target.checked } })} /><i /></label><label className="toggle-row"><span><strong>Cinema Mode</strong><small>Playerを大型化し周囲のcontrastを下げる</small></span><input type="checkbox" checked={settings.layout.cinemaMode} onChange={(e) => app.patchSettings({ layout: { ...settings.layout, cinemaMode: e.target.checked } })} /><i /></label></div></section>
    <section className="settings-section"><div className="settings-title"><Home /><div><h2>Home Sections</h2><p>0件のSectionは設定にかかわらず自動で隠れます。</p></div></div><div className="order-list">{settings.homeOrder.map((key, index) => <div key={key}><label><input type="checkbox" checked={!settings.homeHidden.includes(key)} onChange={(e) => app.patchSettings({ homeHidden: e.target.checked ? settings.homeHidden.filter((item) => item !== key) : [...settings.homeHidden, key] })} />{({ continue: '続きから見る', inbox: 'Watch Inbox', new: '新着', recommended: 'あなた向け', categories: 'よく見るカテゴリ', favorites: '最近お気に入り' } as Record<string, string>)[key]}</label><button className="icon-button" disabled={index === 0} onClick={() => app.patchSettings({ homeOrder: move(settings.homeOrder, index, -1) })}><ArrowUp /></button><button className="icon-button" disabled={index === settings.homeOrder.length - 1} onClick={() => app.patchSettings({ homeOrder: move(settings.homeOrder, index, 1) })}><ArrowDown /></button></div>)}</div></section>
    <section className="settings-section"><div className="settings-title"><PanelLeft /><div><h2>Sidebar</h2><p>Home・Search・Library・Settingsは常に表示します。</p></div></div><div className="order-list">{settings.layout.sidebarOrder.map((key, index) => { const core = ['home', 'search', 'library', 'settings'].includes(key); return <div key={key}><label><input type="checkbox" disabled={core} checked={core || !settings.layout.sidebarHidden.includes(key)} onChange={(e) => app.patchSettings({ layout: { ...settings.layout, sidebarHidden: e.target.checked ? settings.layout.sidebarHidden.filter((item) => item !== key) : [...settings.layout.sidebarHidden, key] } })} />{key}</label><button className="icon-button" disabled={index === 0} onClick={() => app.patchSettings({ layout: { ...settings.layout, sidebarOrder: move(settings.layout.sidebarOrder, index, -1) } })}><ArrowUp /></button><button className="icon-button" disabled={index === settings.layout.sidebarOrder.length - 1} onClick={() => app.patchSettings({ layout: { ...settings.layout, sidebarOrder: move(settings.layout.sidebarOrder, index, 1) } })}><ArrowDown /></button></div> })}</div></section>
    <section className="settings-section"><div className="settings-title"><Filter /><div><h2>Content Filtering</h2><p>BlacklistはHome・Search・Recommendation・Auto Addへ適用し、保存済みLibrary item自体は削除しません。</p></div></div><div className="setting-grid"><label className="setting-item"><span>Blocked Video IDs</span><textarea value={settings.blacklist.videos.join('\n')} onChange={(e) => app.patchSettings({ blacklist: { ...settings.blacklist, videos: e.target.value.split(/\s+/).filter(Boolean) } })} placeholder="1行に1 ID" /></label><label className="setting-item"><span>Blocked Channel IDs</span><textarea value={settings.blacklist.channels.join('\n')} onChange={(e) => app.patchSettings({ blacklist: { ...settings.blacklist, channels: e.target.value.split(/\s+/).filter(Boolean) } })} /></label><label className="setting-item"><span>Blocked Keywords</span><textarea value={settings.blacklist.keywords.join('\n')} onChange={(e) => app.patchSettings({ blacklist: { ...settings.blacklist, keywords: e.target.value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean) } })} /></label><label className="setting-item"><span>Whitelist Channel IDs</span><textarea value={settings.whitelistChannels.join('\n')} onChange={(e) => app.patchSettings({ whitelistChannels: e.target.value.split(/\s+/).filter(Boolean) })} /></label><label className="toggle-row"><span><strong>Whitelist-only mode</strong><small>Blacklistが常に優先</small></span><input type="checkbox" checked={settings.whitelistOnly} onChange={(e) => app.patchSettings({ whitelistOnly: e.target.checked })} /><i /></label><label className="setting-item"><span>Cache soft limit</span><select value={settings.cacheLimitMb} onChange={(e) => app.patchSettings({ cacheLimitMb: Number(e.target.value) as 100 | 250 | 500 })}><option value="100">100 MB</option><option value="250">250 MB</option><option value="500">500 MB</option></select></label></div></section>
    <section className="settings-section"><div className="settings-title"><Eye /><div><h2>Playback</h2><p>Video → Channel → Globalの優先順位で速度を解決します。</p></div></div><div className="setting-grid"><label className="setting-item"><span>Global rate</span><select value={settings.playback.globalRate} onChange={(e) => app.patchSettings({ playback: { ...settings.playback, globalRate: Number(e.target.value) } })}>{[0.5, 0.75, 1, 1.25, 1.5, 1.75, 2].map((rate) => <option value={rate} key={rate}>{rate}x</option>)}</select></label><div className="setting-item"><span>Speed presets（最大8）</span><div className="segmented speed-preset-settings">{[0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2].map((rate) => <button type="button" aria-pressed={settings.playback.speedPresets.includes(rate)} className={settings.playback.speedPresets.includes(rate) ? 'active' : ''} onClick={() => toggleSpeedPreset(rate)} key={rate}>{rate}x</button>)}</div></div><label className="setting-item"><span>Seek</span><select value={settings.playback.seekSeconds} onChange={(e) => app.patchSettings({ playback: { ...settings.playback, seekSeconds: Number(e.target.value) as 5 | 10 | 15 | 30 } })}>{[5, 10, 15, 30].map((seconds) => <option key={seconds} value={seconds}>{seconds}秒</option>)}</select></label><label className="setting-item"><span>BOOST</span><select value={settings.playback.boostMode} onChange={(e) => app.patchSettings({ playback: { ...settings.playback, boostMode: e.target.value as 'next' | 'maximum' } })}><option value="next">Next Available</option><option value="maximum">Maximum Available</option></select></label><label className="toggle-row"><span><strong>Continuous Play</strong><small>動画終了時にQueueの次を再生</small></span><input type="checkbox" checked={settings.playback.continuousPlay} onChange={(e) => app.patchSettings({ playback: { ...settings.playback, continuousPlay: e.target.checked } })} /><i /></label></div></section>
    <section className="settings-section"><div className="settings-title"><Cloud /><div><h2>Google / Cloud Sync</h2><p>任意・Opt-in。TokenはlocalStorageへ保存せず、Logout後もLocal dataを保持します。</p></div></div>{supabase ? <div className={`connection-card ${cloudIdentity ? 'connected' : ''}`}><ShieldCheck /><div><strong>{cloudIdentity === undefined ? 'Cloud sessionを確認中' : cloudIdentity ? 'Google / Supabase connected' : 'Supabase configuration detected'}</strong><span>{cloudIdentity ?? 'Google OAuthで接続すると、YouTube subscriptionsとRLS保護されたSyncを利用できます。'}</span></div>{cloudIdentity ? <><label className="toggle-row cloud-opt-in"><span><strong>Cloud Sync</strong><small>この端末のUser Dataを明示的に同期対象にする</small></span><input type="checkbox" checked={settings.cloudSync} onChange={(e) => app.patchSettings({ cloudSync: e.target.checked })} /><i /></label><button className="primary-button" disabled={syncing || !settings.cloudSync} onClick={() => void runSync()}><RefreshCw className={syncing ? 'spin' : ''} />{syncing ? '同期中' : '今すぐ同期'}</button><button className="text-button" onClick={() => void disconnectCloud()}>Logout</button></> : <button className="secondary-button" disabled={cloudIdentity === undefined} onClick={() => void connectGoogle()}><LogIn />Googleで接続</button>}</div> : <div className="connection-card"><Database /><div><strong>Local-only mode</strong><span>VITE_SUPABASE_URL / ANON_KEY未設定。すべてのlocal機能は利用できます。</span></div></div>}</section>
    <section className="settings-section"><div className="settings-title"><Activity /><div><h2>Diagnostics</h2><p>視聴内容は第三者Telemetryへ送信しません。</p></div></div><div className="diagnostic-summary"><span>App <strong>{APP_VERSION}</strong></span><span>DB schema <strong>v{DB_VERSION}</strong></span><span>Network <strong>{app.online ? 'Online' : 'Offline'}</strong></span></div>{diagnostics.length ? <div className="diagnostic-list">{diagnostics.slice(0, 8).map((event) => <div key={event.id}><span>{event.category}</span><strong>{event.message}</strong><time>{new Date(event.at).toLocaleTimeString()}</time></div>)}</div> : <p className="muted-copy">このsessionに記録されたfailureはありません。</p>}</section>
    <section className="settings-section danger-zone"><div className="settings-title"><Trash2 /><div><h2>Data management</h2><p>CacheとUser Dataは分離されています。</p></div></div><div className="danger-actions"><button className="secondary-button" onClick={() => void dbClear('cache')}><Database />Cacheを削除</button><button className="danger-button" onClick={() => void clearLocal()}><Trash2 />この端末のデータも削除</button></div></section>
  </div>
}
